# config/production.yml

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  database: ${DB_NAME}
  pool_size: 30
  max_overflow: 10

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

market_data:
  websocket_url: ${WEBSOCKET_URL}
